name: Build UACMe

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build UACMe Win32
      working-directory: Source
      run: msbuild uacme.sln /p:Configuration=Release /p:Platform=Win32

    - name: Build UACMe x64
      working-directory: Source
      run: msbuild uacme.sln /p:Configuration=Release /p:Platform=x64

    - name: List output files
      run: |
        dir Source\output\Win32\Release\
        dir Source\output\x64\Release\

    - name: Upload built payloads
      uses: actions/upload-artifact@v4
      with:
        name: UACMe-Binaries
        path: |
          Source\output\Win32\Release\
          Source\output\x64\Release\
