name: Build UACMe

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build all UACMe modules (x64)
      working-directory: Source
      run: msbuild uacme.sln /p:Configuration=Release /p:Platform=x64

    - name: List built payloads
      run: |
        dir Source\*\output\x64\Release\ /b

    - name: Upload built payloads
      uses: actions/upload-artifact@v4
      with:
        name: UACMe-Payloads-x64
        path: |
          Source\Yuubari\output\x64\Release\UacInfo64.exe
          Source\Naka\output\x64\Release\Naka64.exe
          Source\Fubuki\output\x64\Release\Fubuki64.dll
          Source\Akagi\output\x64\Release\Akagi64.exe
